### ISSUE TITLE
Uncaught exception for `tryUpdateFunction` and `funcScopes`

### ISSUE THREAD

**Issue by Raynos** [Raynos/jsig#11]
```
russfrank@rf-C02MN4WKFD57:~/uber/batched-immediate (*) (!)
> npm run type-check

> batched-immediate@0.0.0 type-check /Users/russfrank/uber/batched-immediate
> jsig index.js

Fatal Exception:  { message: 'Cannot read property \'funcScopes\' of undefined',
  stackLine: '    at ProgramMeta.tryUpdateFunction (/Users/russfrank/uber/batched-immediate/node_modules/jsig/type-checker/meta.js:576:20)',
  rawStack:
   [ 'TypeError: Cannot read property \'funcScopes\' of undefined',
     '    at ProgramMeta.tryUpdateFunction (/Users/russfrank/uber/batched-immediate/node_modules/jsig/type-checker/meta.js:576:20)',
     '    at ASTVerifier.verifyAssignmentExpression (/Users/russfrank/uber/batched-immediate/node_modules/jsig/type-checker/ast-verifier.js:289:24)',
     '    at ASTVerifier.verifyNode (/Users/russfrank/uber/batched-immediate/node_modules/jsig/type-checker/ast-verifier.js:41:21)',
     '    at ProgramMeta.verifyNode (/Users/russfrank/uber/batched-immediate/node_modules/jsig/type-checker/meta.js:263:30)',
     '    at ASTVerifier.verifyExpressionStatement (/Users/russfrank/uber/batched-immediate/node_modules/jsig/type-checker/ast-verifier.js:256:22)',
     '    at ASTVerifier.verifyNode (/Users/russfrank/uber/batched-immediate/node_modules/jsig/type-checker/ast-verifier.js:39:21)',
     '    at ProgramMeta.verifyNode (/Users/russfrank/uber/batched-immediate/node_modules/jsig/type-checker/meta.js:263:30)',
     '    at ASTVerifier.verifyBlockStatement (/Users/russfrank/uber/batched-immediate/node_modules/jsig/type-checker/ast-verifier.js:250:19)',
     '    at ASTVerifier.verifyNode (/Users/russfrank/uber/batched-immediate/node_modules/jsig/type-checker/ast-verifier.js:37:21)',
     '    at ProgramMeta.verifyNode (/Users/russfrank/uber/batched-immediate/node_modules/jsig/type-checker/meta.js:263:30)' ] }
was processing the following text:

this.setImmediate = boundBatchedSetImmediate

on: /Users/russfrank/uber/batched-immediate/index.js:79

index.js
Found error: jsig.verify.missing-definition
@3: Cannot find external definition for module: assert.

2.
3. var assert = require('assert');
4.

index.js
Found error: jsig.verify.unknown-identifier
@68: Could not find identifier assert.

67. BatchedImmediate.prototype.setStatsd = function setStatsd(statsd) {
68.     assert(
69.         typeof statsd === 'object' &&
70.         typeof statsd.immediateGauge === 'function' &&
71.         typeof statsd.immediateTiming === 'function',
72.         'expected statsd client instance'
73.     );
74.

index.js
Found error: jsig.verify.found-unexpected-function
@83: Expected boundBatchedSetImmediate to not be a function. Expected null | Function but found Function.

82.     var self = this;
83.     function boundBatchedSetImmediate(fn) {
84.         self.batchedSetImmediate(fn);
85.     }
86.

Expected : null | Function
Actual   : Function

Found (3) errors
```

**Comment by Raynos** [comment]
This is now fixed in master.
